usethis::use_roxygen_md()
usethis::use_pipe()

usethis::use_package("dplyr")
usethis::use_package("readr")
usethis::use_package("tidyr")
usethis::use_package("lubridate")
usethis::use_package("cli")
usethis::use_package("rlang")
library(magrittr)

usethis::use_package("ggplot2")
usethis::use_package("zoo")
usethis::use_package("tsibble")
usethis::use_package("fable")
usethis::use_package("feasts")

usethis::use_r("load_sales_data")
usethis::use_r("validate_sales_ts")
usethis::use_r("clean_sales_ts")
